// Generated by CoffeeScript 1.7.1
var ScheduleView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App.state('Schedule', {
  url: '/products/:id/consume',
  parent: 'xooma'
});

ScheduleView = (function(_super) {
  __extends(ScheduleView, _super);

  function ScheduleView() {
    return ScheduleView.__super__.constructor.apply(this, arguments);
  }

  ScheduleView.prototype.template = '#schedule-template';

  ScheduleView.prototype.ui = {
    intake: '.intake',
    form: '#consume',
    scheduleid: 'input[name="scheduleid"]',
    servings: '.servings',
    responseMessage: '.aj-response-message'
  };

  ScheduleView.prototype.events = {
    'click @ui.servings': function(e) {
      var meta_id, qty;
      e.preventDefault();
      console.log(meta_id = $(e.target).parent().attr('data-value'));
      console.log(qty = $(e.target).parent().attr('data-qty'));
      return ScheduleView.prototype.update_occurrences(meta_id, qty);
    },
    'click @ui.intake': function(e) {
      var data, i, meta_id, occurr, product, qty;
      occurr = this.model.get('occurrence').length;
      i = 0;
      $.each(occurr, function(ind, val) {
        var expected, occurrence;
        occurrence = _.has(val, "occurrence");
        expected = _.has(val, "expected");
        if (occurrence === true && expected === true) {
          return i++;
        }
      });
      e.preventDefault();
      meta_id = $('#meta_id').val();
      qty = $('#qty').val();
      console.log(data = $('#schduleid').val());
      product = this.model.get('id');
      if (parseInt(i) < parseInt(occurr)) {
        return $.ajax({
          method: 'POST',
          data: 'meta_id=' + meta_id + '&qty=' + qty,
          url: "" + _SITEURL + "/wp-json/intakes/" + (App.currentUser.get('ID')) + "/products/" + product,
          success: this.successHandler,
          error: this.erroraHandler
        });
      } else {
        return this.ui.responseMessage.text("Servings are done!!!!");
      }
    }
  };

  ScheduleView.successHandler = function(response, status, xhr) {
    return console.log(response);
  };

  ScheduleView.prototype.serializeData = function() {
    var data, no_servings, occurr, product_type, qty;
    data = ScheduleView.__super__.serializeData.call(this);
    console.log(data.day = moment().format("dddd"));
    console.log(data.today = moment().format("MMMM Do YYYY"));
    qty = this.model.get('qty');
    occurr = this.model.get('occurrence');
    product_type = this.model.get('product_type');
    product_type = product_type.toLowerCase();
    no_servings = [];
    $.each(occurr, function(ind, val) {
      var expected, i, newClass, occurrence, servings;
      console.log(occurrence = _.has(val, "occurrence"));
      console.log(occurr[ind].meta_id);
      console.log(expected = _.has(val, "expected"));
      if (occurrence === true && expected === true) {
        console.log(newClass = product_type + '_occurred_class');
      } else if (occurrence === false && expected === true) {
        console.log(newClass = product_type + '_expected_class');
        ScheduleView.prototype.create_occurrences(val);
      } else if (occurrence === true && expected === false) {
        console.log(newClass = product_type + '_bonus_class');
      }
      i = 0;
      servings = [];
      while (i < qty[ind].qty) {
        servings.push({
          newClass: newClass
        });
        i++;
      }
      no_servings.push({
        servings: servings,
        schedule: val.schedule_id,
        meta_id: val.meta_id,
        qty: qty[ind].qty
      });
      return data.no_servings = no_servings;
    });
    data.original = product_type + '_expected_class';
    return data;
  };

  ScheduleView.prototype.create_occurrences = function(val) {
    console.log(val);
    $('#meta_id').val(0);
    return $('#qty').val(val.qty);
  };

  ScheduleView.prototype.update_occurrences = function(meta_id, qty) {
    if (meta_id === "") {
      meta_id = 0;
    }
    $('#meta_id').val(parseInt(meta_id));
    return $('#qty').val(qty);
  };

  return ScheduleView;

})(Marionette.ItemView);

App.ScheduleCtrl = (function(_super) {
  __extends(ScheduleCtrl, _super);

  function ScheduleCtrl() {
    this.successHandler = __bind(this.successHandler, this);
    return ScheduleCtrl.__super__.constructor.apply(this, arguments);
  }

  ScheduleCtrl.prototype.initialize = function(options) {
    var product, productId, productModel, products, productsColl;
    if (options == null) {
      options = {};
    }
    productId = this.getParams();
    product = parseInt(productId[0]);
    products = [];
    App.homexProductsColl.each(function(val) {
      return $.each(val.get('products'), function(index, value) {
        return products.push(value);
      });
    });
    productsColl = new Backbone.Collection(products);
    productModel = productsColl.where({
      id: parseInt(productId[0])
    });
    return this._showView(productModel[0]);
  };

  ScheduleCtrl.prototype.successHandler = function(response, status, xhr) {
    var model;
    model = new Backbone.Model(response);
    return this._showView(model);
  };

  ScheduleCtrl.prototype._showView = function(productModel) {
    console.log(productModel);
    return this.show(new ScheduleView({
      model: productModel
    }));
  };

  return ScheduleCtrl;

})(Ajency.RegionController);
