// Generated by CoffeeScript 1.7.1
var AppStates, MeasurementsView, PersonalInfoView, ProfileView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Marionette.RegionControllers.prototype.controllers = Xoomapp;

Xoomapp.LoginCtrl = Ajency.LoginCtrl;

ProfileView = (function(_super) {
  __extends(ProfileView, _super);

  function ProfileView() {
    return ProfileView.__super__.constructor.apply(this, arguments);
  }

  ProfileView.prototype.template = '<a class="btn btn-primary" href="#/profile/personal-info">Personal Info</a> <a class="btn btn-primary" href="#/profile/measurements">Measurements</a> <div ui-region></div>';

  return ProfileView;

})(Marionette.LayoutView);

Xoomapp.ProfileCtrl = (function(_super) {
  __extends(ProfileCtrl, _super);

  function ProfileCtrl() {
    return ProfileCtrl.__super__.constructor.apply(this, arguments);
  }

  ProfileCtrl.prototype.initialize = function() {
    return this.show(new ProfileView);
  };

  return ProfileCtrl;

})(Marionette.RegionController);

PersonalInfoView = (function(_super) {
  __extends(PersonalInfoView, _super);

  function PersonalInfoView() {
    return PersonalInfoView.__super__.constructor.apply(this, arguments);
  }

  PersonalInfoView.prototype.template = 'My Personal info view';

  return PersonalInfoView;

})(Marionette.LayoutView);

Xoomapp.PersonalInfoCtrl = (function(_super) {
  __extends(PersonalInfoCtrl, _super);

  function PersonalInfoCtrl() {
    return PersonalInfoCtrl.__super__.constructor.apply(this, arguments);
  }

  PersonalInfoCtrl.prototype.initialize = function() {
    return this.show(new PersonalInfoView);
  };

  return PersonalInfoCtrl;

})(Marionette.RegionController);

MeasurementsView = (function(_super) {
  __extends(MeasurementsView, _super);

  function MeasurementsView() {
    return MeasurementsView.__super__.constructor.apply(this, arguments);
  }

  MeasurementsView.prototype.template = 'My Measurements';

  return MeasurementsView;

})(Marionette.LayoutView);

Xoomapp.MeasurementsCtrl = (function(_super) {
  __extends(MeasurementsCtrl, _super);

  function MeasurementsCtrl() {
    return MeasurementsCtrl.__super__.constructor.apply(this, arguments);
  }

  MeasurementsCtrl.prototype.initialize = function() {
    return this.show(new MeasurementsView);
  };

  return MeasurementsCtrl;

})(Marionette.RegionController);

AppStates = (function(_super) {
  __extends(AppStates, _super);

  function AppStates() {
    return AppStates.__super__.constructor.apply(this, arguments);
  }

  AppStates.prototype.appStates = {
    'login': true,
    'profile': {
      url: '/profile'
    },
    'personalInfo': {
      url: '/personal-info',
      parent: 'profile'
    },
    'measurements': {
      parent: 'profile'
    }
  };

  return AppStates;

})(Marionette.AppStates);

window.App = new Marionette.Application;

App.addInitializer(function() {
  this.states = new AppStates({
    app: App
  });
  Backbone.history.start();
  return this.states.navigate('#/login', true);
});

App.start();
