// Generated by CoffeeScript 1.7.1
window.App = new Marionette.Application;

this.mainRegion = new Marionette.Region({
  el: '#main-region'
});

this.profileapp = new Xoomapp.ProfilePersonalInfoController({
  region: this.mainRegion
});

console.log(Xoomapp);

App.start();
