// Generated by CoffeeScript 1.7.1
App.state('addProducts', {
  url: '/add-products',
  parent: 'xooma',
  resolve: function(stateName, params) {
    return {
      userModel: App.currentUser
    };
  }
});
