// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Xoomapp.MeasurementController = (function(_super) {
  __extends(MeasurementController, _super);

  function MeasurementController() {
    return MeasurementController.__super__.constructor.apply(this, arguments);
  }

  MeasurementController.prototype.initialize = function() {
    this.user = this._get_measurement_details();
    this.view = new Xoomapp.MeasurementView;
    return this.show(this.view);
  };

  MeasurementController.prototype._get_measurement_details = function() {
    return $.ajax({
      method: 'GET',
      url: SITEURL + '/wp-json/measurements/2',
      data: '',
      success: function(response) {},
      error: function(error) {
        return $('.response_msg').text("Something went wrong");
      }
    });
  };

  return MeasurementController;

})(Ajency.RegionController);
