// Generated by CoffeeScript 1.7.1
var AddProductsView, NoProductsChildView, ProductChildView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App.state('AddProducts', {
  url: '/products',
  parent: 'xooma'
});

ProductChildView = (function(_super) {
  __extends(ProductChildView, _super);

  function ProductChildView() {
    return ProductChildView.__super__.constructor.apply(this, arguments);
  }

  ProductChildView.prototype.tagName = 'li';

  ProductChildView.prototype.template = '<a class="cbp-vm-image" href="#"><img src="{{image}}"></a> <h3 class="cbp-vm-title">{{name}}</h3> <div class="cbp-vm-details"> {{description}} </div> <a id="{{id}}"  class="cbp-vm-icon cbp-vm-add add-product" href="#/product/{{id}}/edit">Add Product</a>';

  ProductChildView.prototype.ui = {
    addProduct: '.add-product'
  };

  ProductChildView.prototype.initialize = function() {
    return this.$el.prop("id", 'product' + this.model.get("id"));
  };

  return ProductChildView;

})(Marionette.ItemView);

NoProductsChildView = (function(_super) {
  __extends(NoProductsChildView, _super);

  function NoProductsChildView() {
    return NoProductsChildView.__super__.constructor.apply(this, arguments);
  }

  NoProductsChildView.prototype.template = 'Awesome. You have added all products. Have fun';

  return NoProductsChildView;

})(Marionette.ItemView);

AddProductsView = (function(_super) {
  __extends(AddProductsView, _super);

  function AddProductsView() {
    return AddProductsView.__super__.constructor.apply(this, arguments);
  }

  AddProductsView.prototype["class"] = 'animated fadeIn';

  AddProductsView.prototype.template = '#add-product-template';

  AddProductsView.prototype.childView = ProductChildView;

  AddProductsView.prototype.childViewContainer = 'ul.products-list';

  AddProductsView.prototype.emptyView = NoProductsChildView;

  AddProductsView.prototype.events = {
    'click .grid': function(e) {
      return e.preventDefault();
    }
  };

  AddProductsView.prototype.onShow = function() {
    return $.getScript(_SITEURL + "/html/html/assets/js/cbpViewModeSwitch.js", function(item) {});
  };

  return AddProductsView;

})(Marionette.CompositeView);

App.AddProductsCtrl = (function(_super) {
  __extends(AddProductsCtrl, _super);

  function AddProductsCtrl() {
    this.errorHandler = __bind(this.errorHandler, this);
    this._showProducts = __bind(this._showProducts, this);
    return AddProductsCtrl.__super__.constructor.apply(this, arguments);
  }

  AddProductsCtrl.prototype.initialize = function(options) {
    if (options == null) {
      options = {};
    }
    this.show(this.parent().getLLoadingView());
    if (App.productCollection.length === 0) {
      return App.productCollection.fetch().done(this._showProducts).fail(this.errorHandler);
    } else {
      return this._showProducts();
    }
  };

  AddProductsCtrl.prototype._showProducts = function() {
    var collectionArr, filteredCollection, userProducts;
    userProducts = App.currentUser.get('products');
    collectionArr = App.productCollection.where({
      active_value: '1'
    });
    App.productCollection.reset(collectionArr);
    filteredCollection = App.productCollection.clone();
    return this.show(new AddProductsView({
      collection: filteredCollection
    }));
  };

  AddProductsCtrl.prototype.errorHandler = function() {
    $('.alert').remove();
    return $('.aj-response-message').addClass('alert alert-danger').text("Products could not be loaded!");
  };

  return AddProductsCtrl;

})(Ajency.RegionController);
