// Generated by CoffeeScript 1.7.1
(function() {
  var PersonalInfoView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PersonalInfoView = (function(_super) {
    __extends(PersonalInfoView, _super);

    function PersonalInfoView() {
      return PersonalInfoView.__super__.constructor.apply(this, arguments);
    }

    PersonalInfoView.prototype.template = 'Personal Info details here';

    return PersonalInfoView;

  })(Marionette.ItemView);

  XoomaApp.ProfileCtrl = (function(_super) {
    __extends(ProfileCtrl, _super);

    function ProfileCtrl() {
      return ProfileCtrl.__super__.constructor.apply(this, arguments);
    }

    return ProfileCtrl;

  })(Ajency.RegionController);

  XoomaApp.PersonalInfoCtrl = (function(_super) {
    __extends(PersonalInfoCtrl, _super);

    function PersonalInfoCtrl() {
      return PersonalInfoCtrl.__super__.constructor.apply(this, arguments);
    }

    PersonalInfoCtrl.prototype.initialize = function(options) {
      return this.show(new PersonalInfoView);
    };

    return PersonalInfoCtrl;

  })(Ajency.RegionController);

}).call(this);
