// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

App.ProfilePersonalInfoCtrl = (function(_super) {
  __extends(ProfilePersonalInfoCtrl, _super);

  function ProfilePersonalInfoCtrl() {
    return ProfilePersonalInfoCtrl.__super__.constructor.apply(this, arguments);
  }

  ProfilePersonalInfoCtrl.prototype.initialize = function(options) {
    return this.show(new ProfilePersonalInfoView);
  };

  return ProfilePersonalInfoCtrl;

})(Ajency.RegionController);
