// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  XoomaApp.ProfileStates = (function(_super) {
    __extends(ProfileStates, _super);

    function ProfileStates() {
      return ProfileStates.__super__.constructor.apply(this, arguments);
    }

    ProfileStates.prototype.appStates = {
      'profile': {
        url: '/profile/:id'
      },
      'personalInfo': {
        url: '/personal-info',
        parent: 'profile'
      },
      'measurements': {
        url: '/measurements',
        parent: 'profile'
      }
    };

    return ProfileStates;

  })(Marionette.AppStates);

}).call(this);
