// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

App.ProfilePersonalInfoCtrl = (function(_super) {
  __extends(ProfilePersonalInfoCtrl, _super);

  function ProfilePersonalInfoCtrl() {
    this._showView = __bind(this._showView, this);
    return ProfilePersonalInfoCtrl.__super__.constructor.apply(this, arguments);
  }

  ProfilePersonalInfoCtrl.prototype.initialize = function(options) {
    return App.currentUser.getProfile().done(this._showView).fail(this.errorHandler);
  };

  ProfilePersonalInfoCtrl.prototype._showView = function(userModel) {
    return this.show(new ProfilePersonalInfoView({
      model: userModel
    }));
  };

  ProfilePersonalInfoCtrl.prototype.errorHandler = function(error) {
    this.region = new Marionette.Region({
      el: '#nofound-template'
    });
    return new Ajency.HTTPRequestCtrl({
      region: this.region
    });
  };

  return ProfilePersonalInfoCtrl;

})(Marionette.RegionController);
