// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Xoomapp.ProfilePersonalInfoController = (function(_super) {
  __extends(ProfilePersonalInfoController, _super);

  function ProfilePersonalInfoController() {
    return ProfilePersonalInfoController.__super__.constructor.apply(this, arguments);
  }

  ProfilePersonalInfoController.prototype.initialize = function() {
    this.user = this._get_user_details();
    this.view = new Xoomapp.ProfilePersonalInfoView(this.user);
    return this.show(this.view);
  };

  ProfilePersonalInfoController.prototype._get_user_details = function() {
    return $.ajax({
      method: 'GET',
      url: SITEURL + '/wp-json/profiles/2',
      data: '',
      success: function(response) {
        var user_model;
        user_model = new Backbone.Model;
        user_model.set('xooma_member_id', response.xooma_member_id);
        user_model.set('name', response.name);
        user_model.set('email_id', response.email);
        user_model.set('image', response.image);
        user_model.set('gender', response.gender);
        user_model.set('phone_no', response.phone_no);
        user_model.set('timezone', response.timezone);
        user_model.set('attachment_id', response.attachment_id);
        return user_model;
      },
      error: function(error) {
        return $('.response_msg').text("Something went wrong");
      }
    });
  };

  return ProfilePersonalInfoController;

})(Ajency.RegionController);
