// Generated by CoffeeScript 1.7.1
var ProfileMeasurementsView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ProfileMeasurementsView = (function(_super) {
  __extends(ProfileMeasurementsView, _super);

  function ProfileMeasurementsView() {
    return ProfileMeasurementsView.__super__.constructor.apply(this, arguments);
  }

  ProfileMeasurementsView.prototype.template = '#profile-measurements-template';

  ProfileMeasurementsView.prototype.className = 'animated fadeIn';

  ProfileMeasurementsView.prototype.onShow = function() {
    return $("#add_measurements").validate({
      submitHandler: function(form) {
        $.ajax({
          method: 'POST',
          url: _SITEURL + '/wp-json/measurements/2',
          data: $('#add_measurements').serialize(),
          success: function(response) {
            console.log(response);
            if (response.status === 404) {
              return $('.response_msg').text("Something went wrong");
            } else {
              return $('.response_msg').text("User details saved successfully");
            }
          },
          error: function(error) {
            return $('.response_msg').text("Something went wrong");
          }
        });
        return false;
      }
    });
  };

  return ProfileMeasurementsView;

})(Marionette.ItemView);
