// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(document).ready(function($) {
    App.state('login1').state('universities', {
      url: '/universities/:type'
    });
    App.addInitializer(function() {
      App.currentUser.set('caps', {
        'access_login1': true,
        'access_universities': true
      });
      return Backbone.history.start();
    });
    return App.start();
  });

}).call(this);
