// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(document).ready(function($) {
    App.state('login').state('xooma', {
      url: '/'
    }).state('ProfilePersonalInfo', {
      url: '/profile/personal-info',
      parent: 'xooma'
    }).state('profileMeasurement', {
      url: '/profile/measurements',
      ctrl: 'ProfileMeasurementsCtrl',
      parent: 'xooma'
    });
    App.addInitializer(function() {
      return Backbone.history.start();
    });
    return App.start();
  });

}).call(this);
