// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _.extend(Marionette.Application.prototype, {
    appStates: {},
    state: function(name, def) {
      if (def == null) {
        def = {};
      }
      this.appStates[name] = def;
      return this;
    },
    registerStates: function() {
      Marionette.RegionControllers.prototype.controllers = this;
      _.extend(Marionette.AppStates.prototype, {
        appStates: this.appStates
      });
      return new Marionette.AppStates({
        app: this
      });
    },
    controller: function(name, ctrlPrototype) {
      var CtrlClass;
      if (_.isFunction(ctrlPrototype)) {
        CtrlClass = ctrlPrototype;
      } else {
        CtrlClass = (function(_super) {
          __extends(CtrlClass, _super);

          function CtrlClass() {
            return CtrlClass.__super__.constructor.apply(this, arguments);
          }

          return CtrlClass;

        })(Ajency.RegionController);
        _.extend(CtrlClass.prototype, ctrlPrototype);
      }
      this[name] = CtrlClass;
      return this;
    }
  });

}).call(this);
