// Generated by CoffeeScript 1.7.1
App.LoginCtrl = Ajency.LoginCtrl;

App.NothingFoundCtrl = Ajency.NothingFoundCtrl;

_.extend(Ajency.CurrentUser.prototype, {
  saveMeasurements: function(measurements) {
    var _successHandler;
    _successHandler = (function(_this) {
      return function(resp) {
        return _this.set('measurements', measurements);
      };
    })(this);
    return $.ajax({
      method: 'PUT',
      url: "" + _SITEURL + "/wp-json/users/" + (App.currentUser.get('ID')) + "/measurements",
      data: measurements,
      success: _successHandler
    });
  },
  getFacebookPicture: function() {
    var options;
    options = {
      "redirect": false,
      "height": "200",
      "type": "normal",
      "width": "200"
    };
    return FB.api("/me/picture", options, function(resp) {
      if (resp && !resp.error) {
        return App.currentUser.set('profile_picture', {
          id: 0,
          sizes: {
            thumbnail: {
              url: resp.data.url
            }
          }
        });
      }
    });
  }
});
