// Generated by CoffeeScript 1.7.1
var HomeOtherProductsCtrl, HomeOtherProductsView, HomeView, HomeX2OCtrl, HomeX2OView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

HomeOtherProductsView = (function(_super) {
  __extends(HomeOtherProductsView, _super);

  function HomeOtherProductsView() {
    return HomeOtherProductsView.__super__.constructor.apply(this, arguments);
  }

  HomeOtherProductsView.prototype.template = '<div>dsfs</div>';

  return HomeOtherProductsView;

})(Marionette.ItemView);

HomeOtherProductsCtrl = (function(_super) {
  __extends(HomeOtherProductsCtrl, _super);

  function HomeOtherProductsCtrl() {
    return HomeOtherProductsCtrl.__super__.constructor.apply(this, arguments);
  }

  HomeOtherProductsCtrl.prototype.initialize = function() {
    console.log("aaaaaaaaaaaaaaaaa");
    return this.show(new HomeOtherProductsView);
  };

  return HomeOtherProductsCtrl;

})(Ajency.RegionController);

HomeX2OView = (function(_super) {
  __extends(HomeX2OView, _super);

  function HomeX2OView() {
    return HomeX2OView.__super__.constructor.apply(this, arguments);
  }

  HomeX2OView.prototype.template = '<div>dsfs</div>';

  return HomeX2OView;

})(Marionette.ItemView);

HomeX2OCtrl = (function(_super) {
  __extends(HomeX2OCtrl, _super);

  function HomeX2OCtrl() {
    return HomeX2OCtrl.__super__.constructor.apply(this, arguments);
  }

  HomeX2OCtrl.prototype.initialize = function() {
    console.log("aaaaaaaaaaaaaaaaa");
    return this.show(new HomeX2OView);
  };

  return HomeX2OCtrl;

})(Ajency.RegionController);

HomeView = (function(_super) {
  __extends(HomeView, _super);

  function HomeView() {
    return HomeView.__super__.constructor.apply(this, arguments);
  }

  HomeView.prototype["class"] = 'animated fadeIn';

  HomeView.prototype.template = '#home-template';

  return HomeView;

})(Marionette.ItemView);

App.HomeCtrl = (function(_super) {
  __extends(HomeCtrl, _super);

  function HomeCtrl() {
    return HomeCtrl.__super__.constructor.apply(this, arguments);
  }

  HomeCtrl.prototype.initialize = function() {
    return this.show(new HomeView);
  };

  return HomeCtrl;

})(Ajency.RegionController);
