// Generated by CoffeeScript 1.7.1
var ListofProductsViewItemview,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ListofProductsViewItemview = (function(_super) {
  __extends(ListofProductsViewItemview, _super);

  function ListofProductsViewItemview() {
    return ListofProductsViewItemview.__super__.constructor.apply(this, arguments);
  }

  ListofProductsViewItemview.prototype.tagName = 'li';

  ListofProductsViewItemview.prototype.template = 'Berry <a data-role="detailbutton" data-style="contactadd"></a>';

  return ListofProductsViewItemview;

})(Marionette.ItemView);

Xoomapp.ListofProductsView = (function(_super) {
  __extends(ListofProductsView, _super);

  function ListofProductsView() {
    return ListofProductsView.__super__.constructor.apply(this, arguments);
  }

  ListofProductsView.prototype.template = '<div> <h4 class="text-center">My Xooma Products</h4> <div class="container"> <div class="row"> <div class="col-md-3"></div> <div class="col-md-6"> <ul id="listofproducts"> </ul> </div> <div class="col-md-3"></div> </div> <br> <!-- NEXT Button --> <button id="next-btn" class="k-primary k-button">Next</button> <!-- NEXT Button --> <br> </div> </div>';

  ListofProductsView.prototype.childView = ListofProductsViewItemview;

  ListofProductsView.prototype.childViewContainer = 'ul#listofproducts';

  return ListofProductsView;

})(Marionette.CompositeView);
