// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Xoomapp.ListofProductsController = (function(_super) {
  __extends(ListofProductsController, _super);

  function ListofProductsController() {
    return ListofProductsController.__super__.constructor.apply(this, arguments);
  }

  ListofProductsController.prototype.initialize = function() {
    this.products = this._get_users_products();
    this.view = new Xoomapp.ListofProductsView(this.products);
    return this.show(this.view);
  };

  ListofProductsController.prototype._get_users_products = function() {
    return $.ajax({
      method: 'GET',
      url: SITEURL + '/wp-json/products',
      data: '',
      success: function(response) {
        return console.log(response);
      },
      error: function(error) {
        return $('.response_msg').text("Something went wrong");
      }
    });
  };

  return ListofProductsController;

})(Ajency.RegionController);
