// Generated by CoffeeScript 1.7.1
var EditProductsView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EditProductsView = (function(_super) {
  __extends(EditProductsView, _super);

  function EditProductsView() {
    this.valueOutput = __bind(this.valueOutput, this);
    this.erroraHandler = __bind(this.erroraHandler, this);
    this.successSave = __bind(this.successSave, this);
    this.erroraHandler = __bind(this.erroraHandler, this);
    this.successHandler = __bind(this.successHandler, this);
    return EditProductsView.__super__.constructor.apply(this, arguments);
  }

  EditProductsView.prototype.template = '#edit-product-template';

  EditProductsView.prototype.ui = {
    schedule: '.schedule',
    servings_diff: 'input[name="servings_diff"]',
    servings_per_day: '.servings_per_day',
    form: '#edit_product',
    reminder_button: '.reminder_button',
    responseMessage: '.aj-response-message',
    cancel: '.cancel',
    rangeSliders: '[data-rangeslider]',
    x2o: 'x2o'
  };

  EditProductsView.prototype.events = {
    'change @ui.rangeSliders': function(e) {
      return this.valueOutput(e.currentTarget);
    },
    'click @ui.cancel': function(e) {
      return App.navigate('#/profile/my-products', true);
    },
    'click @ui.reminder_button': function(e) {
      var html1;
      $(this.ui.reminder_button).removeClass('btn-success');
      $(e.target).addClass('btn-success');
      $('#reminder').val($(e.target).attr('data-reminder'));
      html1 = '<div class="reminder">' + $('.reminder').first().html() + '</div>';
      $('.reminder_div').text("");
      $('.reminder_div').append(html1);
      $('.js__timepicker').each(function(ind, val) {
        return console.log(val.name = 'reminder_time' + ind);
      });
      return $(this.ui.servings_per_day).trigger("change");
    },
    'click .save': function(e) {
      var data, product;
      e.preventDefault();
      data = this.ui.form.serialize();
      product = this.model.get('id');
      return $.ajax({
        method: 'POST',
        url: "" + _SITEURL + "/wp-json/trackers/" + (App.currentUser.get('ID')) + "/products/" + product,
        data: data,
        success: this.successSave,
        error: this.errorSave
      });
    },
    'click .remove': function(e) {
      var product, products;
      product = parseInt(this.model.get('id'));
      products = App.currentUser.get('products');
      if ($.inArray(product, products) > -1) {
        return $.ajax({
          method: 'DELETE',
          url: "" + _SITEURL + "/wp-json/trackers/" + (App.currentUser.get('ID')) + "/products/" + product,
          success: this.successHandler,
          error: this.erroraHandler
        });
      }
    },
    'click @ui.schedule': function(e) {
      $(this.ui.schedule).removeClass('btn-primary');
      $(e.target).addClass('btn-primary');
      $('#timeset').val($(e.target).attr('data-time'));
      if ($(e.target).attr('data-time') === 'Once') {
        return $('.second').hide();
      } else {
        return $('.second').show();
      }
    },
    'click @ui.servings_diff ': function(e) {
      var html, i, servings;
      if ($(this.ui.servings_diff).prop('checked') === true) {
        $(e.target).val('1');
        $('#check').val('1');
        servings = $('.servings_per_day').val();
        html = "";
        i = 1;
        while (i <= servings) {
          html += '<div class="qtyper">' + $('.qtyper').first().html() + '</div>';
          i++;
        }
        $('.qty_per_servings_div').text("");
        $('.qty_per_servings_div').append(html);
        $('.qty_per_servings').each(function(ind, val) {
          val.name = 'qty_per_servings' + ind;
          return val.id = 'qty_per_servings' + ind;
        });
      } else {
        $(this.ui.servings_diff).prop('val', 0);
        $('#check').val('0');
        html = '<div class="qtyper">' + $('.qtyper').first().html() + '</div>';
        $('.qty_per_servings_div').text("");
        $('.qty_per_servings_div').append(html);
        $('.qty_per_servings').each(function(ind, val) {
          val.name = 'qty_per_servings' + ind;
          return val.id = 'qty_per_servings' + ind;
        });
      }
      return $('.js__timepicker').pickatime();
    },
    'change @ui.servings_per_day ': function(e) {
      var html, html1, i, servings;
      if (parseInt($(e.target).val()) === 1) {
        $(this.ui.servings_diff).prop('disabled', true);
        $(this.ui.servings_diff).prop('checked', false);
        $(this.ui.servings_diff).prop('val', 0);
        servings = $('.servings_per_day').val();
        html = '<div class="qtyper">' + $('.qtyper').first().html() + '</div>';
        html1 = '<div class="reminder">' + $('.reminder').first().html() + '</div>';
        $('.qty_per_servings_div').text("");
        $('.reminder_div').text("");
        $('.qty_per_servings_div').append(html);
        $('.reminder_div').append(html1);
        $('.qty_per_servings').each(function(ind, val) {
          val.name = 'qty_per_servings' + ind;
          return val.id = 'qty_per_servings' + ind;
        });
        $('.js__timepicker').each(function(ind, val) {
          return val.name = 'reminder_time' + ind;
        });
      } else if ($(this.ui.servings_diff).prop('checked') === true) {
        $(this.ui.servings_diff).prop('disabled', false);
        servings = $('.servings_per_day').val();
        html = "";
        i = 1;
        while (i <= servings) {
          html += '<div class="qtyper">' + $('.qtyper').first().html() + '</div>';
          i++;
        }
        $('.qty_per_servings_div').text("");
        $('.qty_per_servings_div').append(html);
        $('.qty_per_servings').each(function(ind, val) {
          console.log(val.name = 'qty_per_servings' + ind);
          return val.id = 'qty_per_servings' + ind;
        });
        this.showReminders();
      }
      return $('.js__timepicker').pickatime();
    },
    'change .no_of_container': function(e) {
      var cnt;
      cnt = parseInt($(e.target).val()) * parseInt(this.model.get('total'));
      $('#available').val(cnt);
      return $('.available').text(cnt);
    }
  };

  EditProductsView.prototype.showReminders = function() {
    var html1, i, servings;
    if (parseInt($('#reminder').val()) === 1) {
      $(this.ui.servings_diff).prop('disabled', false);
      servings = $('.servings_per_day').val();
      html1 = "";
      i = 1;
      while (i <= servings) {
        html1 += '<div class="reminder">' + $('.reminder').first().html() + '</div>';
        i++;
      }
      $('.reminder_div').text("");
      $('.reminder_div').append(html1);
      return $('.js__timepicker').each(function(ind, val) {
        return val.name = 'reminder_time' + ind;
      });
    }
  };

  EditProductsView.prototype.successHandler = function(response, status, xhr) {
    var products;
    if (xhr.status === 200) {
      products = App.currentUser.get('products');
      products.remove(response);
    }
    return App.navigate('#/profile/my-products', true);
  };

  EditProductsView.prototype.erroraHandler = function(response, status, xhr) {
    this.ui.responseMessage.text("Something went wrong");
    return $('html, body').animate({
      scrollTop: 0
    }, 'slow');
  };

  EditProductsView.prototype.successSave = function(response, status, xhr) {
    var products;
    if (xhr.status === 201) {
      response = parseInt(response);
      products = App.currentUser.get('products');
      if (typeof products === 'undefined') {
        products = [];
      }
      products = _.union(products, [response]);
      App.currentUser.set('products', products);
    }
    return App.navigate('#/profile/my-products', true);
  };

  EditProductsView.prototype.erroraHandler = function(response, status, xhr) {
    this.ui.responseMessage.text("Could not delete the prodcut");
    return $('html, body').animate({
      scrollTop: 0
    }, 'slow');
  };

  EditProductsView.prototype.serializeData = function() {
    var data, frequecy, qty, reminder_flag;
    data = EditProductsView.__super__.serializeData.call(this);
    if (this.model.get('time_set') === 'asperbmi') {
      qty = this.model.get('qty');
      data.x2o = qty[0].qty;
    }
    frequecy = this.model.get('frequency_value');
    if (parseInt(frequecy) === 1) {
      data.anytime = '';
      data.schedule = 'disabled';
      data.anytimeclass = 'btn-primary';
      data.scheduleclass = '';
    } else {
      data.anytime = 'disabled';
      data.schedule = '';
      data.anytimeclass = '';
      data.scheduleclass = 'btn-primary';
      if (this.model.get('time_set') === 'Once') {
        data.once = 'btn-primary';
        data.twice = '';
      } else {
        data.once = '';
        data.twice = 'btn-primary';
      }
    }
    reminder_flag = this.model.get('reminder_flag');
    if (reminder_flag === void 0 || reminder_flag === 0 || reminder_flag === 'true') {
      data["default"] = 'btn-success';
      data.success = '';
    } else {
      data["default"] = '';
      data.success = 'btn-success';
    }
    return data;
  };

  EditProductsView.prototype.onShow = function() {
    var container, product, products, reminder_flag;
    $('.js__timepicker').pickatime();
    this.ui.rangeSliders.each((function(_this) {
      return function(index, ele) {
        return _this.valueOutput(ele);
      };
    })(this));
    this.ui.rangeSliders.rangeslider({
      polyfill: false
    });
    if (parseInt(this.model.get('frequency_value')) === 1 && this.model.get('time_set') !== 'asperbmi') {
      $('.schedule_data').hide();
      $('.asperbmi').hide();
      $('.servings_per_day option[value="' + this.model.get('time_set') + '"]').prop("selected", true);
      if (parseInt(this.model.get('time_set')) === 1) {
        $(this.ui.servings_diff).prop('disabled', true);
      }
      this.showAnytimeData(this.model);
    } else if (parseInt(this.model.get('frequency_value')) === 2) {
      $('.anytime').hide();
      $('.asperbmi').hide();
      this.showScheduleData(this.model);
    } else {
      $('.schedule_data').hide();
      $('.anytime').hide();
    }
    $('#timeset').val(this.model.get('time_set'));
    container = this.model.get('no_of_container');
    reminder_flag = this.model.get('reminder_flag');
    $('#reminder').val(reminder_flag);
    $('.no_of_container option[value="' + container + '"]').prop("selected", true);
    product = parseInt(this.model.get('id'));
    products = App.currentUser.get('products');
    if ($.inArray(product, products) === -1) {
      return $('.remove').hide();
    }
  };

  EditProductsView.prototype.valueOutput = function(element) {
    return $(element).parent().find("output").html($(element).val());
  };

  EditProductsView.prototype.showScheduleData = function(model) {
    var product, products;
    product = parseInt(model.get('id'));
    products = App.currentUser.get('products');
    if ($.inArray(product, products) > -1) {
      return this.showEditScheduleData(model);
    } else {
      return this.showAddScheduleData(model);
    }
  };

  EditProductsView.prototype.showAddScheduleData = function(model) {
    var qty, whendata;
    if (this.model.get('time_set') === 'Once') {
      $('.second').hide();
      qty = this.model.get('serving_size').split('|');
      whendata = this.model.get('when').split('|');
      $('.qty0 option[value="' + qty[0] + '"]').prop("selected", true);
      return $('.when0 option[value="' + whendata[0] + '"]').prop("selected", true);
    } else {
      qty = this.model.get('serving_size').split('|');
      whendata = this.model.get('when').split('|');
      $('.qty0 option[value="' + qty[0] + '"]').prop("selected", true);
      $('.when0 option[value="' + whendata[0] + '"]').prop("selected", true);
      $('.qty1 option[value="' + qty[1] + '"]').prop("selected", true);
      return $('.when1 option[value="' + whendata[1] + '"]').prop("selected", true);
    }
  };

  EditProductsView.prototype.showEditScheduleData = function(model) {
    var qty;
    qty = model.get('qty');
    if (this.model.get('time_set') === 'Once') {
      $('.second').hide();
      $('.qty0 option[value="' + qty[0].qty + '"]').prop("selected", true);
      return $('.when0 option[value="' + qty[0].when + '"]').prop("selected", true);
    } else {
      $('.qty0 option[value="' + qty[0].qty + '"]').prop("selected", true);
      $('.when0 option[value="' + qty[0].when + '"]').prop("selected", true);
      $('.qty1 option[value="' + qty[1].qty + '"]').prop("selected", true);
      return $('.when1 option[value="' + qty[1].when + '"]').prop("selected", true);
    }
  };

  EditProductsView.prototype.showAnytimeData = function(model) {
    var product, products, qty;
    product = parseInt(model.get('id'));
    products = App.currentUser.get('products');
    if ($.inArray(product, products) > -1) {
      return this.showServings(model);
    } else {
      qty = model.get('serving_size').split('|');
      return $('.qty_per_servings option[value="' + qty[0] + '"]').prop("selected", true);
    }
  };

  EditProductsView.prototype.showServings = function(model) {
    var qty;
    qty = model.get('qty');
    if (parseInt(model.get('check')) === 1) {
      $(this.ui.servings_diff).prop('checked', true);
      $(this.ui.servings_per_day).trigger("change");
      $('#check').val(1);
      return $.each(qty, function(ind, val) {
        return $('#qty_per_servings' + ind + ' option[value="' + val.qty + '"]').prop("selected", true);
      });
    } else {
      return $('#qty_per_servings0 option[value="' + qty[0].qty + '"]').prop("selected", true);
    }
  };

  return EditProductsView;

})(Marionette.ItemView);

App.EditProductsCtrl = (function(_super) {
  __extends(EditProductsCtrl, _super);

  function EditProductsCtrl() {
    this.successHandler = __bind(this.successHandler, this);
    return EditProductsCtrl.__super__.constructor.apply(this, arguments);
  }

  EditProductsCtrl.prototype.initialize = function(options) {
    var product, productId, productModel, products;
    if (options == null) {
      options = {};
    }
    productId = this.getParams();
    console.log(product = parseInt(productId[0]));
    console.log(products = App.currentUser.get('products'));
    if ($.inArray(product, products) > -1) {
      return $.ajax({
        method: 'GET',
        url: "" + _SITEURL + "/wp-json/trackers/" + (App.currentUser.get('ID')) + "/products/" + product,
        success: this.successHandler,
        error: this.erroraHandler
      });
    } else {
      productModel = App.productCollection.where({
        id: productId[0]
      });
      return this._showView(productModel[0]);
    }
  };

  EditProductsCtrl.prototype._showView = function(productModel) {
    console.log(productModel);
    return this.show(new EditProductsView({
      model: productModel
    }));
  };

  EditProductsCtrl.prototype.successHandler = function(response, status, xhr) {
    var model, pid;
    pid = App.productCollection.where({
      id: response.id
    });
    model = new Backbone.Model(response);
    return this._showView(model);
  };

  return EditProductsCtrl;

})(Ajency.RegionController);
